### ISSUE TITLE
Error: User.getUser failed with sql errors

### ISSUE THREAD

**Issue by faktaochkunskap** [jcoppieters/cody#24]
This is the second time I have this error. It seems to happen after a while. Under development I am using forever with no time settings. So maybe something has stopped running. The front-end is still working. 

If I restart forever the problem is solved.

Error: User.getUser failed with sql errors
   at Query._callback (/home/billgates/Dokument/ipro5/node_modules/cody/models/User.js:78:46)
   at Query.Sequence.end (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
   at Protocol._validateEnqueue (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:218:6)
   at Protocol._enqueue (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:129:13)
   at Connection.query (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/Connection.js:185:25)
   at Controller.query (/home/billgates/Dokument/ipro5/node_modules/cody/controllers/Controller.js:404:19)
   at Function.User.getUser (/home/billgates/Dokument/ipro5/node_modules/cody/models/User.js:77:16)
   at Controller.LoginController.tryLogin (/home/billgates/Dokument/ipro5/node_modules/cody/controllers/LoginController.js:90:13)
   at Controller.LoginController.doRequest (/home/billgates/Dokument/ipro5/node_modules/cody/controllers/LoginController.js:50:10)
   at Application.handToController (/home/billgates/Dokument/ipro5/node_modules/cody/apps/Application.js:308:14)

**Comment by faktaochkunskap** [comment]
Forever log:

- ------------------------------------------------------------------- Mon Mar 30 2015 06:14:42 GMT+0200 (CEST)--
- servePage - path -> /en/login
buildContext -> page -> en/2 - Login
servePage - params ->
{ request: 'login', username: 'super', password: 'empty' }
servePage - session ->
{ cookie:
  { path: '/',
    _expires: Mon Mar 30 2015 07:08:50 GMT+0200 (CEST),
    originalMaxAge: 3600000,
    httpOnly: true },
 pendingContext:
  { params: {},
    path:
     { language: 'en',
       domain: 'dashboard',
       request: '',
       id: '',
       path: 'en/dashboard',
       pagelink: 'en/dashboard',
       link: '/en/dashboard' },
    request: '',
    static: '/static',
    dynamic: '/data',
    fn: '-/cms/dashboard.ejs' },
 login: {} }
servePage - files ->
{}
handToController -> LoginController
LoginController.constructor -> page(2) = Login, request = login
Controller.constructor -> page(2) = Login, request = login
Application.getConnection -> Returning existing connection
{ [Error: Cannot enqueue Query after fatal error.] code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
Error: User.getUser failed with sql errors
   at Query._callback (/home/billgates/Dokument/ipro5/node_modules/cody/models/User.js:78:46)
   at Query.Sequence.end (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
   at Protocol._validateEnqueue (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:218:6)
   at Protocol._enqueue (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:129:13)
   at Connection.query (/home/billgates/Dokument/ipro5/node_modules/cody/node_modules/mysql/lib/Connection.js:185:25)
   at Controller.query (/home/billgates/Dokument/ipro5/node_modules/cody/controllers/Controller.js:404:19)
   at Function.User.getUser (/home/billgates/Dokument/ipro5/node_modules/cody/models/User.js:77:16)
   at Controller.LoginController.tryLogin (/home/billgates/Dokument/ipro5/node_modules/cody/controllers/LoginController.js:90:13)
   at Controller.LoginController.doRequest (/home/billgates/Dokument/ipro5/node_modules/cody/controllers/LoginController.js:50:10)
   at Application.handToController (/home/billgates/Dokument/ipro5/node_modules/cody/apps/Application.js:308:14)

**Comment by jcoppieters** [comment]
Hello,

I’m afraid you’ll have to do a sudo there…
the problem is that mysql times out and that the connection is unilaterally closed by the server, so you end up with a dead socket…

I’m sure someone can fix this, but I came with this quick fix and let’s be honest: if you site isn’t used for 200 days….

I changed my mySQL config file

vi /etc/mysql/my.cnf   #  add
  [client]
  default-character-set=utf8
  [myslqd]
  collation_server=utf8_unicode_ci
  character_set_server=utf8 
  wait_timeout = 31536000
  interactive_timeout = 31536000

Johan.

**Comment by ticup** [comment]
@jcoppieters Should we add this in the default config file? Or maybe it's better to try to open the connection whenever we encounter a dead one?

**Comment by jcoppieters** [comment]
Problem is solvable

- easy: set longer timeout for mysql. It happens only on very very low traffic sites (no requests in more than a day). by setting a longer timeout, you can go up to 200days without a request. It is something the mysql user should do, we can't do it in Cody / node.js

- normal: ping the mysql server once every 6 hours or so. (SetInterval ?)

- hard: check if the socket to mysql is still open before every query. Feasable, but I think this should be done in the mysql-node implementation, not in Cody.
