### ISSUE TITLE
Unable to install new site 

### ISSUE THREAD

**Issue by tjet-lw** [jcoppieters/cody#40]
Getting this when following the installation guid:
mkdir /Users/Micke/Projects/codysites/codyTest/controllers
mkdir /Users/Micke/Projects/codysites/codyTest/locales
mkdir /Users/Micke/Projects/codysites/codyTest/static
mkdir /Users/Micke/Projects/codysites/codyTest/static/css
mkdir /Users/Micke/Projects/codysites/codyTest/static/images
mkdir /Users/Micke/Projects/codysites/codyTest/static/js
mkdir /Users/Micke/Projects/codysites/codyTest/views
/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
Error: ER_INVALID_DEFAULT: Invalid default value for 'created'
    at Query.Sequence._packetToError (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
    --------------------
    at Protocol._enqueue (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Connection.query (/Users/Micke/Projects/codysites/node_modules/cody/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/Micke/Projects/codysites/node_modules/cody/bin/create_site.js:130:27
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by hmelenok** [comment]
The same issue

**Comment by cotlod** [comment]
Got it to work by changing the default GLOBAL MySQL sql_mode! You need to remove the NO_ZERO_DATE mode using this command

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE',''));

Cheers!

**Comment by ticup** [comment]
That's great news @cotlod!
Can you tell us which version of MySql you're running please?
Thanks.

**Comment by cotlod** [comment]
5.7.9

Cheers!

**Comment by ticup** [comment]
Seems like they did change some defaults recently (as of 5.7), also 'NO_ZERO_DATE' is now deprecated: http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes
We'll need to change the default value for the rows that use Date.

Thanks a lot for catching this @cotlod!

**Comment by cotlod** [comment]
:+1:

**Comment by ticup** [comment]
This is 'fixed' in 9ac30d25767a845e16dedb4274f9fbe83e6c29f0 .
