### ISSUE TITLE
crash on image upload

### ISSUE THREAD

**Issue by wannesmarynen** [jcoppieters/cody#48]
when i upload an image the server crashes

**Comment by wannesmarynen** [comment]
i get the error:

TypeError: this.feedBack is not a function
    at /home/wannes/Desktop/codytest/node_modules/cody/controllers/TreeController.js:275:20
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by BerendPronk** [comment]
Have you already changed the "datapath" property in the `config.json` file?
